
spring:
  application:
    name: course-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:course-ms}
    username: root
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_URL:localhost:8761}/eureka/

server:
  port: 8082